name: CI

on:
  push:
    branches:
      - main
      - 'release-*'
      - 'feature-*'
  pull_request:
    branches:
      - "*"

jobs:
  build:
    name: ${{ matrix.os }} - Go ${{ matrix.go_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      # If you want to matrix build, you can append the following list.
      matrix:
        go_version:
          - '1.23.0'
        os:
          - ubuntu-latest
          # - macos-latest  # 可选：添加macOS测试
          # - windows-latest  # 可选：添加Windows测试

    env:
      DING_TOKEN: ${{ secrets.DING_TOKEN }}
      DING_SIGN: ${{ secrets.DING_SIGN }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go_version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go_version }}
          cache: true
          cache-dependency-path: go.sum

      - name: Verify Go installation
        run: go version

      - name: Get dependencies
        run: |
          go mod tidy
          # for imports-formatter
          go install github.com/dubbogo/tools/cmd/imports-formatter@latest

      - name: Format Code
        run: |
          go fmt ./...
          GOROOT=$(go env GOROOT) imports-formatter
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "Code formatting issues found:"
            git diff
            exit 1
          fi

      - name: Check License Header
        uses: apache/skywalking-eyes/header@e1a02359b239bd28de3f6d35fdc870250fa513d5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mode: check

      - name: Restore Go version after license check
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go_version }}
          cache: true
          cache-dependency-path: go.sum

      - name: Check Go version
        run: |
          go version

      - name: Switch Dubbo-go version
        run: |
          # Acquire information of branch
          if [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
            BRANCH=${{github.base_ref}}
          elif [ "$GITHUB_EVENT_NAME" == "push" ]; then
            BRANCH=$GITHUB_REF_NAME
          else
            echo "$GITHUB_EVENT_NAME event is unsupported right now"
            exit 1
          fi
          echo "EVENT = $GITHUB_EVENT_NAME, BRANCH = $BRANCH"
          # Edit the version
          go mod edit -replace=dubbo.apache.org/dubbo-go/v3=dubbo.apache.org/dubbo-go/v3@$BRANCH
          go mod tidy

      - name: Integration Test
        run: |
          ./start_integrate_test.sh
