name: CI

on:
  push:
    branches:
      - main
      - 'release-*'
      - 'feature-*'
  pull_request:
    branches:
      - "*"

jobs:
  build:
    name: ${{ matrix.os }} - Go ${{ matrix.go_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      # If you want to matrix build, you can append the following list.
      matrix:
        go_version:
          - '1.23'
        os:
          - ubuntu-latest
          # - macos-latest  # 可选：添加macOS测试
          # - windows-latest  # 可选：添加Windows测试

    env:
      DING_TOKEN: ${{ secrets.DING_TOKEN }}
      DING_SIGN: ${{ secrets.DING_SIGN }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go_version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go_version }}
          cache: true
          cache-dependency-path: go.sum

      - name: Verify Go installation
        run: go version

      - name: Get dependencies
        run: |
          go mod tidy
          # for imports-formatter
          go install github.com/dubbogo/tools/cmd/imports-formatter@latest

      - name: Format Code
        run: |
          go fmt ./...
          GOROOT=$(go env GOROOT) imports-formatter
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "Code formatting issues found:"
            git diff
            exit 1
          fi

      - name: Check License Header
        uses: apache/skywalking-eyes/header@e1a02359b239bd28de3f6d35fdc870250fa513d5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mode: check

      - name: Check Go version
        run: |
          go version

      - name: Switch Dubbo-go version
        run: |
          set -e  # 遇到错误立即退出
          
          # Acquire information of branch
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            BRANCH="${{ github.base_ref }}"
          elif [ "${{ github.event_name }}" == "push" ]; then
            BRANCH="${{ github.ref_name }}"
          else
            echo "Unsupported event: ${{ github.event_name }}"
            exit 1
          fi
          
          echo "EVENT = ${{ github.event_name }}, BRANCH = $BRANCH"
          
          # Check if the branch exists in dubbo-go repository before replacing
          if git ls-remote --heads https://github.com/apache/dubbo-go.git "$BRANCH" | grep -q "$BRANCH"; then
            echo "Found branch $BRANCH in dubbo-go repository, using it"
            go mod edit -replace=dubbo.apache.org/dubbo-go/v3=dubbo.apache.org/dubbo-go/v3@$BRANCH
          else
            echo "Branch $BRANCH not found in dubbo-go repository, using default version"
          fi
          
          go mod tidy

      - name: Integration Test
        run: |
          ./start_integrate_test.sh
